[package]
name = "wiener-linien-ogd"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.24"
reqwest = { version = "0.11.16", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
